### PR TITLE
distinguished pre-existing-user exception as new UserExists exception

### PR DESCRIPTION
**Pull request by jmcaine**
It's useful to be able to catch this particular exception for handling the typical use case.

### CODE REVIEW

**Comment by FedericoCeratto** [comment]
@jmcaine thanks for the PR. What is your use-case? Usually users are created through a registration process (see tests./test.py test_prevent_double_registration() ).
Would you mind adding at test for your change?

**Comment by jmcaine** [comment]
Sorry for the long lapse.  I just altered test.py to catch the newly-created exception, rather than the generic AAAException. My use-case is simple: I just want to handle a specific exception, and know that what I'm dealing with is specifically a duplicate-user creation attempt, so that I can tell the person trying to register.  Without a specific exception, I can't be sure that this is the problem (as opposed to some more generic or completely different failure that might occur within the code handling registration).  Hopefully that makes sense. I sync'd my fork and merged; the PR should be good to go if you approve.

**Comment by FedericoCeratto** [comment]
Merging the PR, thank you!

**Comment by jmcaine** [comment]
Wow, that was fast.  Thanks!

**Pull request merged**
